apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-funlife
spec:
  selector:
    matchLabels:
      app: funlife
      ver: v1
  replicas: 2
  template:
    metadata:
      name: pod-funlife
      labels:
        app: funlife
        ver: v1
    spec:
      containers:
        - name: funlife
          image: rkdals213/funlife-front
          imagePullPolicy: Always
          ports:
            - name: port-funlife
              containerPort: 10001
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 500m
              memory: 1024Mi
